[template]
src = "opennms-datasources.xml.tmpl"
dest = "/opt/opennms/etc/opennms-datasources.xml"
keys = [
    "opennms/database",
    "opennms/dbname",
    "opennms/dbuser",
    "opennms/dbpass",
    "postgres",
]
