[[releasenotes-36]]

= What's New in OpenNMS Horizon 36

== Breaking changes

=== File `eventconf.xml` moved to DB
The contents of the file `eventconf.xml` will be stored in the database during the upgrade process and all files in `etc/events` will be moved to `etc_archive`.
These events will not be imported into the database. Please refer to the OpenNMS documentation for information on how to migrate custom events to the database.

=== JoeSNMP removed
The SNMP implementation JoeSNMP was removed in Horizon 36.

=== At least PostgreSQL 14.0 is required

OpenNMS {page-component-title} now requires PostgreSQL 14.x or newer.
If you are running an older version, you must upgrade to PostgreSQL 14 or later.
Attempting a schema upgrade with `install -dis` will result in an error.
If upgrading PostgreSQL to at least version 14 isn’t possible and you’re completely blocked, the -Q flag lets you skip the version check.
Use this only as a last resort, since it may affect compatibility.
Be aware that doing so takes you beyond supported configurations — here be dragons.

=== Ticketing plugin is now automatic

The `OSGiBasedTicketerPlugin` is now the default ticketer plugin.
Ticketing is automatically enabled when an OSGi-based ticketer plugin is installed and disabled when it is removed.
The `NullTicketerPlugin` and the `opennms.ticketer.plugin` property have been removed.

If you have `opennms.ticketer.plugin=org.opennms.netmgt.ticketd.NullTicketerPlugin` in a custom properties file under `etc/opennms.properties.d/`, remove that entry before upgrading.
If you previously set `opennms.ticketer.plugin=org.opennms.netmgt.ticketd.OSGiBasedTicketerPlugin`, that entry is now redundant and can be removed.
The `opennms.alarmTroubleTicketEnabled` property is no longer required but can still be used to explicitly enable or disable ticketing.
