jobs:
  publish:
    docker:
      - image: cimg/python:3.10
    resource_class: small
    environment:
      DOCKER_CLI_EXPERIMENTAL: enabled
    steps:
      - add_ssh_keys:
          fingerprints:
            - "5e:70:a4:1a:f3:9f:39:ca:2a:d9:b5:9a:6c:2b:c3:66"
            - "66:9a:2d:a8:ad:7b:cc:7c:d2:ee:55:94:01:72:ac:2a"
            - "4a:0a:cb:11:a3:33:b1:14:e9:cb:db:41:76:fa:a3:bf"
            - "aa:e8:af:11:e4:78:e7:75:b7:a1:69:d0:c8:17:0c:7a"
      - shallow-clone
      - setup_remote_docker
      - cloudsmith/ensure-api-key
      - cloudsmith/install-cli
      - cached-download:
          url: https://github.com/theupdateframework/notary/releases/download/v0.6.1/notary-Linux-amd64
          file: /usr/local/bin/notary
      - download-download-artifacts
      - run:
          name: download resources from parent jobs
          command: |
            for TYPE in oci rpm deb yml; do
              download-artifacts.pl \
                --vault-layout \
                --include-failed \
                --workflow="${CIRCLE_WORKFLOW_ID}" \
               "${TYPE}" \
               "${CIRCLE_BRANCH}" \
               /tmp/artifacts
            done
      - run:
          name: Import OCI Files
          command: |
            find /tmp/artifacts/oci -name \*.oci | while read -r OCI; do
              docker image load --quiet -i "${OCI}"
            done
      - run:
          name: Publish to Docker Hub
          command: .circleci/scripts/publish-dockerhub.sh
      - run:
          name: Publish to Cloudsmith
          command: .circleci/scripts/publish-cloudsmith.sh
      - run:
          name: Publish to Azure
          command: .circleci/scripts/publish-azure.sh
